services:
  front:
    build: .
    container_name: portfolio
    image: portfolio:latest
    restart: always
    network_mode: 'host'
    environment:
      - CRYPTOCLOUD_API_KEY=${CRYPTOCLOUD_API_KEY}
      - CRYPTOCLOUD_SHOP_ID=${CRYPTOCLOUD_SHOP_ID}
      - UMAMI_ID=${UMAMI_ID}
      - UMAMI_HOST=${UMAMI_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
