services:
  front:
    build: .
    container_name: portfolio
    image: portfolio:latest
    environment:
      - CRYPTOCLOUD_API_KEY=${CRYPTOCLOUD_API_KEY}
      - CRYPTOCLOUD_SHOP_ID=${CRYPTOCLOUD_SHOP_ID}
    ports:
      - "3000:3000"