services:
  front:
    build: .
    container_name: portfolio
    image: portfolio:latest
    restart: always
    network_mode: 'host'
    healthcheck:
      test: ['CMD-SHELL', "curl -f http://localhost:3000/api/healthcheck || echo 'Healthcheck failed: $?'; exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    environment:
      - CRYPTOCLOUD_API_KEY=${CRYPTOCLOUD_API_KEY}
      - CRYPTOCLOUD_SHOP_ID=${CRYPTOCLOUD_SHOP_ID}
      - UMAMI_ID=${UMAMI_ID}
      - UMAMI_HOST=${UMAMI_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
